version: '3'
services:
  db:
    image: postgres:14
    container_name: database-enotulen
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=enotulen_prod
    volumes:
      - database-volume:/var/lib/postgresql/data
    networks:
      - shared-network
    restart: on-failure
  app:
    image: enotulen-be
    environment:
      PORT: 8080
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@enotulen_prod
    links:
      - db
    depends_on:
      - db
    ports:
      - '8080:8080'

volumes:
  database-volume:

networks:
  shared-network: